services:
  - type: web
    name: sarv-infotech
    runtime: python
    buildCommand: ""
    startCommand: "python server.py --port $PORT"
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.12.0
